<a href="https://colab.research.google.com/github/HenriARM/ML/blob/master/rock-paper-scissors-ffnn/rock-paper-scissors-ffnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip install tensorflow==2.0.0
!pip install numpy

In [0]:
import tensorflow as tf
import numpy as np
from tensorflow import keras
from tensorflow.keras.layers import Dense, Activation, Reshape

In [0]:
# Input data: array of 2 opponents with  states 0- rock 1-scisors 2-paper
learn_input = np.array([
  [[1,0,0], [1,0,0]],
  [[0,1,0], [0,1,0]],
  [[0,0,1], [0,0,1]],
  [[1,0,0], [0,1,0]],
  [[1,0,0], [0,0,1]],
  [[0,1,0], [0,0,1]]
])
learn_output = np.array([[1,1],[1,1],[1,1],[1,0],[0,1],[1,0]])

In [0]:
model = keras.models.Sequential([
  Reshape((6,), input_shape=(2, 3,)),
  Dense(12),
  Activation('sigmoid'),
  Dense(2),
  Activation('sigmoid')
])
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['accuracy'])
model.fit(learn_input, learn_output, epochs=10000, batch_size=1, verbose=0)
model.summary()

Model: "sequential_62"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
reshape_23 (Reshape)         (None, 6)                 0         
_________________________________________________________________
dense_46 (Dense)             (None, 12)                84        
_________________________________________________________________
activation_46 (Activation)   (None, 12)                0         
_________________________________________________________________
dense_47 (Dense)             (None, 2)                 26        
_________________________________________________________________
activation_47 (Activation)   (None, 2)                 0         
Total params: 110
Trainable params: 110
Non-trainable params: 0
_________________________________________________________________


In [0]:
test_input = np.array([
  [[0,1,0], [1,0,0]],
  [[0,0,1], [1,0,0]],
  [[0,0,1], [0,1,0]]
])

test_output = np.array([[0,1],[1,0],[0,1]])

print(model.predict(np.array(learn_input, 'float32')))
print(learn_output)

print(model.predict(np.array(test_input, 'float32')))
print(test_output)

[[9.9995816e-01 9.9999869e-01]
 [1.0000000e+00 9.9990296e-01]
 [9.9995834e-01 9.9999857e-01]
 [9.9996513e-01 7.5966120e-05]
 [7.9007143e-05 9.9990332e-01]
 [9.9996400e-01 9.4256742e-05]]
[[1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [1 0]]
[[1.         0.9999565 ]
 [1.         1.        ]
 [1.         0.99996257]]
[[0 1]
 [1 0]
 [0 1]]
